using System.Collections.Generic;

namespace Rubickanov.Codegen.Editor
{
    /// <summary>How a generated member is declared.</summary>
    public enum MemberKind
    {
        /// <summary>Compile-time constant: <c>const</c>. For literals (strings, ints).</summary>
        Const,

        /// <summary>Runtime-initialized field: <c>static readonly</c>. For values from method calls.</summary>
        StaticReadonly,
    }

    /// <summary>A single generated member (a named constant or static-readonly field).</summary>
    public readonly struct ConstMember
    {
        /// <summary>Raw member name; sanitized and de-duplicated by the builder.</summary>
        public readonly string Name;

        /// <summary>C# type of the member, e.g. "string" or "int".</summary>
        public readonly string Type;

        /// <summary>Right-hand-side literal or expression, e.g. <c>"\"Player\""</c> or <c>"8"</c>.</summary>
        public readonly string Value;

        public readonly MemberKind Kind;

        public ConstMember(string name, string type, string value, MemberKind kind = MemberKind.Const)
        {
            Name = name;
            Type = type;
            Value = value;
            Kind = kind;
        }
    }

    /// <summary>A nested class of members, e.g. one animator controller's parameter hashes.</summary>
    public sealed class ConstGroup
    {
        /// <summary>Raw class name; sanitized and de-duplicated against sibling groups.</summary>
        public string Name;

        public readonly List<ConstMember> Members = new();

        public ConstGroup(string name) => Name = name;
    }

    /// <summary>
    /// Emits a static class of constants from a flat member list plus optional nested groups.
    /// Member and group names are sanitized into valid C# identifiers and de-duplicated per scope,
    /// so realistic Unity data (a layer named "UI", two scenes whose names collapse to the same
    /// identifier, ...) can never produce uncompilable output. Pure function — unit-testable
    /// without any Editor asset state.
    /// </summary>
    public static class ConstantsClassBuilder
    {
        /// <summary>
        /// Builds the full source file: auto-generated banner, optional using directives, namespace,
        /// the outer class (named by <paramref name="config"/>), root members, then nested groups.
        /// </summary>
        /// <param name="generatorName">Display name embedded in the banner.</param>
        /// <param name="usings">Using directives to emit before the namespace, or null.</param>
        public static string Build(
            string generatorName,
            GeneratorConfig config,
            IReadOnlyList<ConstMember> rootMembers,
            IReadOnlyList<ConstGroup>? groups = null,
            IReadOnlyList<string>? usings = null)
        {
            var access = config.AccessKeyword;
            var partial = config.MakePartial ? " partial" : string.Empty;

            var writer = new CodeWriter();
            writer.AutoGeneratedHeader(generatorName);
            writer.Line();

            if (usings != null)
            {
                foreach (var u in usings)
                    writer.Line($"using {u};");
                writer.Line();
            }

            writer.OpenBrace($"namespace {config.Namespace}");
            writer.OpenBrace($"{access} static{partial} class {config.ClassName}");

            // Root members and nested-group class names share the outer class scope.
            var usedRoot = new HashSet<string>(System.StringComparer.Ordinal);

            WriteMembers(writer, rootMembers, access, usedRoot);

            if (groups != null && groups.Count > 0)
            {
                if (rootMembers.Count > 0)
                    writer.Line();

                for (var i = 0; i < groups.Count; i++)
                {
                    var group = groups[i];
                    var className = IdentifierSanitizer.MakeUnique(
                        IdentifierSanitizer.Sanitize(group.Name, lowercaseRemainder: false), usedRoot);

                    writer.OpenBrace($"{access} static class {className}");
                    WriteMembers(writer, group.Members, access, new HashSet<string>(System.StringComparer.Ordinal));
                    writer.CloseBrace();

                    if (i < groups.Count - 1)
                        writer.Line();
                }
            }

            writer.CloseBrace();
            writer.CloseBrace();

            return writer.ToString();
        }

        private static void WriteMembers(CodeWriter writer, IReadOnlyList<ConstMember> members, string access,
            ISet<string> used)
        {
            foreach (var member in members)
            {
                var name = IdentifierSanitizer.MakeUnique(
                    IdentifierSanitizer.Sanitize(member.Name, lowercaseRemainder: false), used);
                var modifier = member.Kind == MemberKind.Const ? "const" : "static readonly";
                writer.Line($"{access} {modifier} {member.Type} {name} = {member.Value};");
            }
        }
    }
}
