using System.Collections.Generic;
using NUnit.Framework;
using Rubickanov.Codegen.Editor;

namespace Rubickanov.Codegen.Tests
{
    [TestFixture]
    public class ConstantsClassBuilderTests
    {
        private static GeneratorConfig Config(GeneratedAccess access = GeneratedAccess.Public) => new()
        {
            Namespace = "Game.Generated",
            ClassName = "Layers",
            Access = access,
        };

        [Test]
        public void Build_RootMembers_EmitsHeaderNamespaceClassAndMembers()
        {
            var members = new List<ConstMember>
            {
                new("Player", "string", "\"Player\""),
                new("PlayerIndex", "int", "8"),
            };

            var code = ConstantsClassBuilder.Build("Layers", Config(), members);

            StringAssert.Contains("// <auto-generated>", code);
            StringAssert.Contains("namespace Game.Generated", code);
            StringAssert.Contains("public static class Layers", code);
            StringAssert.Contains("public const string Player = \"Player\";", code);
            StringAssert.Contains("public const int PlayerIndex = 8;", code);
        }

        [Test]
        public void Build_NameRequiringSanitization_ProducesValidIdentifier()
        {
            var members = new List<ConstMember> { new("Main Menu", "string", "\"Main Menu\"") };

            var code = ConstantsClassBuilder.Build("Scenes", Config(), members);

            StringAssert.Contains("public const string MainMenu = \"Main Menu\";", code);
        }

        [Test]
        public void Build_DuplicateNames_DisambiguatedPerScope()
        {
            var members = new List<ConstMember>
            {
                new("Fire", "string", "\"fire\""),
                new("Fire", "string", "\"Fire\""),
            };

            var code = ConstantsClassBuilder.Build("Tags", Config(), members);

            StringAssert.Contains("public const string Fire = \"fire\";", code);
            StringAssert.Contains("public const string Fire_2 = \"Fire\";", code);
        }

        [Test]
        public void Build_InternalAccess_AppliesModifierToClassAndMembers()
        {
            var members = new List<ConstMember> { new("Player", "string", "\"Player\"") };

            var code = ConstantsClassBuilder.Build("Tags", Config(GeneratedAccess.Internal), members);

            StringAssert.Contains("internal static class Layers", code);
            StringAssert.Contains("internal const string Player = \"Player\";", code);
        }

        [Test]
        public void Build_Groups_EmitNestedClassesWithStaticReadonlyMembers()
        {
            var group = new ConstGroup("PlayerController");
            group.Members.Add(new ConstMember(
                "Speed", "int", "Animator.StringToHash(\"Speed\")", MemberKind.StaticReadonly));

            var code = ConstantsClassBuilder.Build(
                "Animator Parameters", Config(), new List<ConstMember>(), new List<ConstGroup> { group },
                new[] { "UnityEngine" });

            StringAssert.Contains("using UnityEngine;", code);
            StringAssert.Contains("public static class PlayerController", code);
            StringAssert.Contains("public static readonly int Speed = Animator.StringToHash(\"Speed\");", code);
        }
    }
}
