using System;
using System.Collections.Generic;
using NUnit.Framework;
using Rubickanov.Localization.Editor;

namespace Rubickanov.Localization.Tests
{
    [TestFixture]
    public class LocalizationKeysGeneratorTests
    {
        private static LocalizationCodeOptions DefaultOptions() => new()
        {
            Namespace = "Game.Loc",
            ClassName = "Loc",
        };

        private static Dictionary<string, List<string>> Table(string name, params string[] keys)
            => new() { [name] = new List<string>(keys) };

        [Test]
        public void GenerateCode_EmitsHeaderNamespaceAndClass()
        {
            var code = LocalizationKeysGenerator.GenerateCode(Table("Strings", "hello"), DefaultOptions());

            StringAssert.Contains("// <auto-generated>", code);
            StringAssert.Contains("namespace Game.Loc", code);
            StringAssert.Contains("public static class Loc", code);
            StringAssert.Contains("using Rubickanov.Localization;", code);
        }

        [Test]
        public void GenerateCode_SimpleKey_EmitsFieldWithFullKey()
        {
            var code = LocalizationKeysGenerator.GenerateCode(Table("Strings", "hello"), DefaultOptions());

            StringAssert.Contains("private const string Table = \"Strings\";", code);
            StringAssert.Contains("public static readonly LocalizationKey Hello = new(Table, \"hello\");", code);
        }

        [Test]
        public void GenerateCode_CaseDifferingSiblings_DisambiguatesFieldNames()
        {
            var code = LocalizationKeysGenerator.GenerateCode(Table("Strings", "item.fire", "item.Fire"), DefaultOptions());

            StringAssert.Contains("public static readonly LocalizationKey Fire = new(Table, \"item.Fire\");", code);
            StringAssert.Contains("public static readonly LocalizationKey Fire_2 = new(Table, \"item.fire\");", code);
        }

        [Test]
        public void GenerateCode_LeafAndNestedClassSameName_DisambiguatesNestedClass()
        {
            var code = LocalizationKeysGenerator.GenerateCode(
                Table("Strings", "menu.settings", "menu.settings.volume"), DefaultOptions());

            StringAssert.Contains("public static readonly LocalizationKey Settings = new(Table, \"menu.settings\");", code);
            StringAssert.Contains("public static class Settings_2", code);
            StringAssert.Contains("public static readonly LocalizationKey Volume = new(Table, \"menu.settings.volume\");", code);
        }

        [Test]
        public void GenerateCode_HyphenAndUnderscoreKeys_DisambiguatesFieldNames()
        {
            var code = LocalizationKeysGenerator.GenerateCode(Table("Strings", "my-key", "my_key"), DefaultOptions());

            StringAssert.Contains("public static readonly LocalizationKey MyKey = new(Table, \"my-key\");", code);
            StringAssert.Contains("public static readonly LocalizationKey MyKey_2 = new(Table, \"my_key\");", code);
        }

        [Test]
        public void GenerateCode_KeySanitizingToTable_DoesNotCollideWithTableConst()
        {
            var code = LocalizationKeysGenerator.GenerateCode(Table("Strings", "table", "other"), DefaultOptions());

            StringAssert.Contains("private const string Table = \"Strings\";", code);
            StringAssert.Contains("public static readonly LocalizationKey Table_2 = new(Table, \"table\");", code);
            StringAssert.DoesNotContain("LocalizationKey Table =", code);
        }

        [Test]
        public void GenerateCode_TableNamesSanitizingToSameClass_DisambiguatesTableClasses()
        {
            var tables = new Dictionary<string, List<string>>
            {
                ["my-table"] = new List<string> { "a" },
                ["my_table"] = new List<string> { "b" },
            };

            var code = LocalizationKeysGenerator.GenerateCode(tables, DefaultOptions());

            StringAssert.Contains("public static class MyTable", code);
            StringAssert.Contains("public static class MyTable_2", code);
        }

        [Test]
        public void GenerateCode_SameInput_IsDeterministic()
        {
            var input = Table("Strings", "item.fire", "item.Fire", "my-key", "my_key", "table");

            var first = LocalizationKeysGenerator.GenerateCode(input, DefaultOptions());
            var second = LocalizationKeysGenerator.GenerateCode(
                Table("Strings", "item.fire", "item.Fire", "my-key", "my_key", "table"), DefaultOptions());

            Assert.AreEqual(first, second);
        }

        [Test]
        public void GenerateCode_NullTables_Throws()
        {
            Assert.Throws<ArgumentNullException>(() => LocalizationKeysGenerator.GenerateCode(null!, DefaultOptions()));
        }

        [Test]
        public void GenerateCode_EmptyNamespace_Throws()
        {
            var options = new LocalizationCodeOptions { Namespace = "", ClassName = "Loc" };

            Assert.Throws<ArgumentException>(() => LocalizationKeysGenerator.GenerateCode(Table("Strings", "a"), options));
        }
    }
}
