using System.Text;

namespace Rubickanov.Codegen.Editor
{
    /// <summary>
    /// Minimal indentation-aware source builder. Tracks brace depth so generators emit nested
    /// classes without hand-managing whitespace. Indents with four spaces per level.
    /// </summary>
    public sealed class CodeWriter
    {
        private const string IndentUnit = "    ";

        private readonly StringBuilder _sb = new();
        private int _depth;

        /// <summary>Appends a line at the current indent, or a blank line when text is empty.</summary>
        public CodeWriter Line(string text = "")
        {
            if (text.Length == 0)
            {
                _sb.Append('\n');
                return this;
            }

            for (var i = 0; i < _depth; i++)
                _sb.Append(IndentUnit);

            _sb.Append(text).Append('\n');
            return this;
        }

        /// <summary>Emits <paramref name="header"/> followed by <c>{</c> and increases indentation.</summary>
        public CodeWriter OpenBrace(string header)
        {
            Line(header);
            Line("{");
            _depth++;
            return this;
        }

        /// <summary>Decreases indentation and emits the matching <c>}</c>.</summary>
        public CodeWriter CloseBrace()
        {
            _depth--;
            Line("}");
            return this;
        }

        /// <summary>
        /// Writes the standard auto-generated banner naming the generator that produced the file.
        /// </summary>
        public CodeWriter AutoGeneratedHeader(string generatorName)
        {
            Line("// <auto-generated>");
            Line($"// This file is auto-generated by Rubickanov Codegen ({generatorName}).");
            Line("// Do not modify manually. Regenerate via Project Settings / Rubickanov Codegen.");
            Line("// </auto-generated>");
            return this;
        }

        public override string ToString() => _sb.ToString();
    }
}
