using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Rubickanov.GameplayTags.Editor
{
    /// <summary>
    /// Generates strongly-typed static tag constants from a <see cref="GameplayTagAsset"/> database.
    /// </summary>
    public static class GameplayTagsGenerator
    {
        private static GameplayTagsGeneratorSettings Settings => GameplayTagsGeneratorSettings.instance;

        [MenuItem("Tools/Generators/Gameplay Tags")]
        public static void GenerateTags()
        {
            var asset = FindTagAsset();
            if (asset == null)
            {
                Debug.LogWarning("[GameplayTagsGenerator] No GameplayTagAsset found.");
                return;
            }

            var registry = new GameplayTagRegistry(asset.TagPaths);
            var names = registry.GetAllNames();

            if (names.Count == 0)
            {
                Debug.LogWarning("[GameplayTagsGenerator] No tags found in database.");
                return;
            }

            var code = GenerateCode(names);
            WriteToFile(code);

            AssetDatabase.Refresh();
            Debug.Log($"[GameplayTagsGenerator] Generated {Settings.OutputPath} with {names.Count} tag(s).");
        }

        private static string GenerateCode(IReadOnlyList<string> names)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated by GameplayTagsGenerator.");
            sb.AppendLine("// Do not modify manually. Run Tools/Generators/Gameplay Tags to regenerate.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using Rubickanov.GameplayTags;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Settings.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {Settings.ClassName}");
            sb.AppendLine("    {");

            // Build tree structure
            var root = BuildTree(names);
            WriteNode(sb, root, "        ");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static TreeNode BuildTree(IReadOnlyList<string> paths)
        {
            var root = new TreeNode("", "");

            foreach (var path in paths)
            {
                var parts = path.Split('.');
                var current = root;

                for (var i = 0; i < parts.Length; i++)
                {
                    var segment = parts[i];
                    var fullPath = string.Join(".", parts, 0, i + 1);

                    if (!current.Children.TryGetValue(segment, out var child))
                    {
                        child = new TreeNode(segment, fullPath);
                        current.Children[segment] = child;
                    }

                    current = child;
                }
            }

            return root;
        }

        private static void WriteNode(StringBuilder sb, TreeNode node, string indent)
        {
            var sortedChildren = node.Children.OrderBy(c => c.Key).ToList();

            for (var i = 0; i < sortedChildren.Count; i++)
            {
                var child = sortedChildren[i].Value;
                var fieldName = SanitizeIdentifier(child.Segment);

                if (child.Children.Count > 0)
                {
                    // Node with children → nested class
                    sb.AppendLine($"{indent}public static class {fieldName}");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    public static readonly GameplayTag Tag = GameplayTagRegistry.Instance.Get(\"{child.FullPath}\");");

                    WriteNode(sb, child, indent + "    ");

                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    // Leaf node → field only
                    sb.AppendLine($"{indent}public static readonly GameplayTag {fieldName} = GameplayTagRegistry.Instance.Get(\"{child.FullPath}\");");
                }

                if (i < sortedChildren.Count - 1)
                    sb.AppendLine();
            }
        }

        private static string SanitizeIdentifier(string input)
        {
            if (string.IsNullOrEmpty(input))
                return "_";

            var sanitized = Regex.Replace(input, @"[^a-zA-Z0-9_]", "_");

            if (char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            sanitized = ToPascalCase(sanitized);

            if (IsCSharpKeyword(sanitized))
                sanitized = "@" + sanitized;

            return sanitized;
        }

        private static string ToPascalCase(string input)
        {
            var parts = input.Split('_', System.StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();

            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(part[0]));
                    if (part.Length > 1)
                        sb.Append(part.Substring(1));
                }
            }

            return sb.Length > 0 ? sb.ToString() : "_";
        }

        private static bool IsCSharpKeyword(string word)
        {
            var keywords = new HashSet<string>
            {
                "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
                "char", "checked", "class", "const", "continue", "decimal", "default",
                "delegate", "do", "double", "else", "enum", "event", "explicit",
                "extern", "false", "finally", "fixed", "float", "for", "foreach",
                "goto", "if", "implicit", "in", "int", "interface", "internal",
                "is", "lock", "long", "namespace", "new", "null", "object", "operator",
                "out", "override", "params", "private", "protected", "public",
                "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
                "stackalloc", "static", "string", "struct", "switch", "this", "throw",
                "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
                "ushort", "using", "virtual", "void", "volatile", "while"
            };

            return keywords.Contains(word.ToLowerInvariant());
        }

        private static void WriteToFile(string content)
        {
            var directory = Path.GetDirectoryName(Settings.OutputPath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(Settings.OutputPath, content);
        }

        private static GameplayTagAsset? FindTagAsset()
        {
            var guids = AssetDatabase.FindAssets("t:GameplayTagAsset");
            if (guids.Length == 0)
                return null;

            var path = AssetDatabase.GUIDToAssetPath(guids[0]);
            return AssetDatabase.LoadAssetAtPath<GameplayTagAsset>(path);
        }

        private sealed class TreeNode
        {
            public string Segment { get; }
            public string FullPath { get; }
            public Dictionary<string, TreeNode> Children { get; } = new();

            public TreeNode(string segment, string fullPath)
            {
                Segment = segment;
                FullPath = fullPath;
            }
        }
    }
}
