using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Rubickanov.GameplayTags.Editor
{
    /// <summary>
    /// Generates strongly-typed static tag constants from <see cref="GameplayTagAsset"/> databases.
    /// </summary>
    public static class GameplayTagsGenerator
    {
        private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal", "default",
            "delegate", "do", "double", "else", "enum", "event", "explicit",
            "extern", "false", "finally", "fixed", "float", "for", "foreach",
            "goto", "if", "implicit", "in", "int", "interface", "internal",
            "is", "lock", "long", "namespace", "new", "null", "object", "operator",
            "out", "override", "params", "private", "protected", "public",
            "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
            "stackalloc", "static", "string", "struct", "switch", "this", "throw",
            "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
            "ushort", "using", "virtual", "void", "volatile", "while"
        };

        private static GameplayTagsGeneratorSettings Settings => GameplayTagsGeneratorSettings.instance;

        [MenuItem("Tools/Generators/Gameplay Tags")]
        public static void GenerateTags()
        {
            var assets = FindAllTagAssets();
            if (assets.Count == 0)
            {
                Debug.LogWarning("[GameplayTagsGenerator] No GameplayTagAsset found.");
                return;
            }

            var allPaths = assets.SelectMany(a => a.TagPaths).Distinct().ToArray();
            var registry = new GameplayTagRegistry(allPaths);
            var names = registry.GetAllNames();

            if (names.Count == 0)
            {
                Debug.LogWarning("[GameplayTagsGenerator] No tags found in database.");
                return;
            }

            var options = new GenerateCodeOptions
            {
                Namespace = Settings.Namespace,
                ClassName = Settings.ClassName,
                AccessModifier = Settings.AccessModifier,
                MakePartial = Settings.MakePartial,
            };

            var code = GenerateCode(names, options);
            WriteToFile(code);

            AssetDatabase.Refresh();
            Debug.Log($"[GameplayTagsGenerator] Generated {Settings.OutputPath} with {names.Count} tag(s) from {assets.Count} asset(s).");
        }

        /// <summary>
        /// Pure code generator. Produces a C# source string from a sorted list of tag paths.
        /// Deterministic: identical input + options yield identical output.
        /// </summary>
        public static string GenerateCode(IReadOnlyList<string> names, GenerateCodeOptions options)
        {
            if (names == null) throw new ArgumentNullException(nameof(names));
            if (string.IsNullOrEmpty(options.Namespace)) throw new ArgumentException("Namespace must be non-empty.", nameof(options));
            if (string.IsNullOrEmpty(options.ClassName)) throw new ArgumentException("ClassName must be non-empty.", nameof(options));

            var access = string.IsNullOrEmpty(options.AccessModifier) ? "public" : options.AccessModifier;
            var partial = options.MakePartial ? " partial" : "";

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated by GameplayTagsGenerator.");
            sb.AppendLine("// Do not modify manually. Run Tools/Generators/Gameplay Tags to regenerate.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using Rubickanov.GameplayTags;");
            sb.AppendLine();
            sb.AppendLine($"namespace {options.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    {access} static{partial} class {options.ClassName}");
            sb.AppendLine("    {");

            var root = BuildTree(names);
            WriteNode(sb, root, "        ", access);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static TreeNode BuildTree(IReadOnlyList<string> paths)
        {
            var root = new TreeNode("", "");

            foreach (var path in paths)
            {
                var current = root;
                var start = 0;

                while (start <= path.Length)
                {
                    var dot = path.IndexOf('.', start);
                    var end = dot < 0 ? path.Length : dot;
                    var segment = path.Substring(start, end - start);
                    var fullPath = path.Substring(0, end);

                    if (!current.Children.TryGetValue(segment, out var child))
                    {
                        child = new TreeNode(segment, fullPath);
                        current.Children[segment] = child;
                    }

                    current = child;

                    if (dot < 0)
                        break;

                    start = dot + 1;
                }
            }

            return root;
        }

        private static void WriteNode(StringBuilder sb, TreeNode node, string indent, string access)
        {
            var sortedChildren = new List<KeyValuePair<string, TreeNode>>(node.Children);
            sortedChildren.Sort((a, b) => StringComparer.Ordinal.Compare(a.Key, b.Key));

            // Distinct registry tags can sanitize to the same C# identifier (e.g. "fire" and
            // "Fire" both PascalCase to "Fire"). Members in one scope must be unique or the
            // generated file won't compile, so disambiguate collisions per scope.
            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            for (var i = 0; i < sortedChildren.Count; i++)
            {
                var child = sortedChildren[i].Value;
                var fieldName = MakeUniqueIdentifier(SanitizeIdentifier(child.Segment), usedNames);

                if (child.Children.Count > 0)
                {
                    sb.AppendLine($"{indent}{access} static class {fieldName}");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    {access} static readonly GameplayTag Tag = GameplayTagRegistry.Instance.Get(\"{child.FullPath}\");");

                    WriteNode(sb, child, indent + "    ", access);

                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    sb.AppendLine($"{indent}{access} static readonly GameplayTag {fieldName} = GameplayTagRegistry.Instance.Get(\"{child.FullPath}\");");
                }

                if (i < sortedChildren.Count - 1)
                    sb.AppendLine();
            }
        }

        private static string MakeUniqueIdentifier(string name, HashSet<string> used)
        {
            if (used.Add(name))
                return name;

            // Preserve a leading "@" keyword escape on the suffixed form (e.g. "@class" -> "@class_2").
            var hasEscape = name.StartsWith("@", StringComparison.Ordinal);
            var bare = hasEscape ? name.Substring(1) : name;
            var prefix = hasEscape ? "@" : string.Empty;

            int n = 2;
            string candidate;
            do { candidate = $"{prefix}{bare}_{n++}"; } while (!used.Add(candidate));
            return candidate;
        }

        private static string SanitizeIdentifier(string input)
        {
            if (string.IsNullOrEmpty(input))
                return "_";

            var sanitized = Regex.Replace(input, @"[^a-zA-Z0-9_]", "_");

            if (char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            sanitized = ToPascalCase(sanitized);

            if (IsCSharpKeyword(sanitized))
                sanitized = "@" + sanitized;

            return sanitized;
        }

        private static string ToPascalCase(string input)
        {
            var parts = input.Split('_', StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();

            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(part[0]));
                    if (part.Length > 1)
                        sb.Append(part.Substring(1));
                }
            }

            return sb.Length > 0 ? sb.ToString() : "_";
        }

        private static bool IsCSharpKeyword(string word)
        {
            return CSharpKeywords.Contains(word.ToLowerInvariant());
        }

        private static void WriteToFile(string content)
        {
            var directory = Path.GetDirectoryName(Settings.OutputPath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(Settings.OutputPath, content);
        }

        private static List<GameplayTagAsset> FindAllTagAssets()
        {
            var guids = AssetDatabase.FindAssets("t:GameplayTagAsset");
            var assets = new List<GameplayTagAsset>();

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var asset = AssetDatabase.LoadAssetAtPath<GameplayTagAsset>(path);
                if (asset != null)
                    assets.Add(asset);
            }

            return assets;
        }

        private sealed class TreeNode
        {
            public string Segment { get; }
            public string FullPath { get; }
            public Dictionary<string, TreeNode> Children { get; } = new();

            public TreeNode(string segment, string fullPath)
            {
                Segment = segment;
                FullPath = fullPath;
            }
        }
    }

    /// <summary>Options for <see cref="GameplayTagsGenerator.GenerateCode"/>.</summary>
    public struct GenerateCodeOptions
    {
        /// <summary>C# namespace for the generated class.</summary>
        public string Namespace;

        /// <summary>Name of the generated static class.</summary>
        public string ClassName;

        /// <summary>Access modifier ("public" or "internal").</summary>
        public string AccessModifier;

        /// <summary>If true, the generated class is declared <c>partial</c>.</summary>
        public bool MakePartial;
    }
}
