using System;
using System.Collections.Generic;
using System.Text;
using Rubickanov.Codegen.Editor;

namespace Rubickanov.GameplayTags.Editor
{
    /// <summary>
    /// Pure code generator for strongly-typed static tag constants. Identifier sanitization and
    /// collision handling are delegated to the shared <see cref="IdentifierSanitizer"/>; tag paths
    /// preserve interior casing (lowercaseRemainder: false), so "DoT" stays "DoT".
    /// </summary>
    public static class GameplayTagsGenerator
    {
        /// <summary>
        /// Produces a C# source string from a sorted list of tag paths.
        /// Deterministic: identical input + options yield identical output.
        /// </summary>
        public static string GenerateCode(IReadOnlyList<string> names, GenerateCodeOptions options)
        {
            if (names == null) throw new ArgumentNullException(nameof(names));
            if (string.IsNullOrEmpty(options.Namespace)) throw new ArgumentException("Namespace must be non-empty.", nameof(options));
            if (string.IsNullOrEmpty(options.ClassName)) throw new ArgumentException("ClassName must be non-empty.", nameof(options));

            var access = string.IsNullOrEmpty(options.AccessModifier) ? "public" : options.AccessModifier;
            var partial = options.MakePartial ? " partial" : "";

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated by GameplayTagsGenerator.");
            sb.AppendLine("// Do not modify manually. Run Tools/Generators/Gameplay Tags to regenerate.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using Rubickanov.GameplayTags;");
            sb.AppendLine();
            sb.AppendLine($"namespace {options.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    {access} static{partial} class {options.ClassName}");
            sb.AppendLine("    {");

            var root = BuildTree(names);
            WriteNode(sb, root, "        ", access, reserveTag: false);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static TreeNode BuildTree(IReadOnlyList<string> paths)
        {
            var root = new TreeNode("", "");

            foreach (var path in paths)
            {
                var current = root;
                var start = 0;

                while (start <= path.Length)
                {
                    var dot = path.IndexOf('.', start);
                    var end = dot < 0 ? path.Length : dot;
                    var segment = path.Substring(start, end - start);
                    var fullPath = path.Substring(0, end);

                    if (!current.Children.TryGetValue(segment, out var child))
                    {
                        child = new TreeNode(segment, fullPath);
                        current.Children[segment] = child;
                    }

                    current = child;

                    if (dot < 0)
                        break;

                    start = dot + 1;
                }
            }

            return root;
        }

        private static void WriteNode(StringBuilder sb, TreeNode node, string indent, string access, bool reserveTag)
        {
            var sortedChildren = new List<KeyValuePair<string, TreeNode>>(node.Children);
            sortedChildren.Sort((a, b) => StringComparer.Ordinal.Compare(a.Key, b.Key));

            // Distinct registry tags can sanitize to the same C# identifier (e.g. "fire" and
            // "Fire" both PascalCase to "Fire"). Members in one scope must be unique or the
            // generated file won't compile, so disambiguate collisions per scope.
            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            // Nested-class scopes auto-emit a "Tag" field (see below). Reserve it so a child
            // segment that sanitizes to "Tag" (path "Damage.Tag") gets suffixed instead of
            // colliding with the emitted field. The top-level class has no such field.
            if (reserveTag)
                usedNames.Add("Tag");

            for (var i = 0; i < sortedChildren.Count; i++)
            {
                var child = sortedChildren[i].Value;
                var fieldName = IdentifierSanitizer.MakeUnique(
                    IdentifierSanitizer.Sanitize(child.Segment, lowercaseRemainder: false), usedNames);

                if (child.Children.Count > 0)
                {
                    sb.AppendLine($"{indent}{access} static class {fieldName}");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    {access} static readonly GameplayTag Tag = GameplayTagRegistry.Instance.Get(\"{child.FullPath}\");");

                    WriteNode(sb, child, indent + "    ", access, reserveTag: true);

                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    sb.AppendLine($"{indent}{access} static readonly GameplayTag {fieldName} = GameplayTagRegistry.Instance.Get(\"{child.FullPath}\");");
                }

                if (i < sortedChildren.Count - 1)
                    sb.AppendLine();
            }
        }

        private sealed class TreeNode
        {
            public string Segment { get; }
            public string FullPath { get; }
            public Dictionary<string, TreeNode> Children { get; } = new();

            public TreeNode(string segment, string fullPath)
            {
                Segment = segment;
                FullPath = fullPath;
            }
        }
    }

    /// <summary>Options for <see cref="GameplayTagsGenerator.GenerateCode"/>.</summary>
    public struct GenerateCodeOptions
    {
        /// <summary>C# namespace for the generated class.</summary>
        public string Namespace;

        /// <summary>Name of the generated static class.</summary>
        public string ClassName;

        /// <summary>Access modifier ("public" or "internal").</summary>
        public string AccessModifier;

        /// <summary>If true, the generated class is declared <c>partial</c>.</summary>
        public bool MakePartial;
    }
}
