using System;
using NUnit.Framework;
using Rubickanov.GameplayTags.Editor;

namespace Rubickanov.GameplayTags.Tests
{
    [TestFixture]
    public class GameplayTagsGeneratorTests
    {
        private static GenerateCodeOptions DefaultOptions() => new()
        {
            Namespace = "Game.Tags",
            ClassName = "GameTags",
            AccessModifier = "public",
            MakePartial = false,
        };

        [Test]
        public void GenerateCode_EmitsHeaderAndNamespace()
        {
            var code = GameplayTagsGenerator.GenerateCode(new[] { "Damage" }, DefaultOptions());

            StringAssert.Contains("// <auto-generated>", code);
            StringAssert.Contains("namespace Game.Tags", code);
            StringAssert.Contains("public static class GameTags", code);
            StringAssert.Contains("using Rubickanov.GameplayTags;", code);
        }

        [Test]
        public void GenerateCode_LeafTag_EmitsField()
        {
            var code = GameplayTagsGenerator.GenerateCode(new[] { "Damage" }, DefaultOptions());

            StringAssert.Contains("public static readonly GameplayTag Damage = GameplayTagRegistry.Instance.Get(\"Damage\");", code);
        }

        [Test]
        public void GenerateCode_NestedTag_EmitsNestedClassWithTagField()
        {
            var code = GameplayTagsGenerator.GenerateCode(new[] { "Damage", "Damage.Fire" }, DefaultOptions());

            StringAssert.Contains("public static class Damage", code);
            StringAssert.Contains("public static readonly GameplayTag Tag = GameplayTagRegistry.Instance.Get(\"Damage\");", code);
            StringAssert.Contains("public static readonly GameplayTag Fire = GameplayTagRegistry.Instance.Get(\"Damage.Fire\");", code);
        }

        [Test]
        public void GenerateCode_InternalAccessModifier_AppliesToAllDeclarations()
        {
            var options = DefaultOptions();
            options.AccessModifier = "internal";

            var code = GameplayTagsGenerator.GenerateCode(new[] { "Damage", "Damage.Fire" }, options);

            StringAssert.Contains("internal static class GameTags", code);
            StringAssert.Contains("internal static class Damage", code);
            StringAssert.Contains("internal static readonly GameplayTag Tag", code);
            StringAssert.Contains("internal static readonly GameplayTag Fire", code);
            StringAssert.DoesNotContain("public static", code);
        }

        [Test]
        public void GenerateCode_MakePartial_EmitsPartialKeyword()
        {
            var options = DefaultOptions();
            options.MakePartial = true;

            var code = GameplayTagsGenerator.GenerateCode(new[] { "Damage" }, options);

            StringAssert.Contains("public static partial class GameTags", code);
        }

        [Test]
        public void GenerateCode_DeterministicForSameInput()
        {
            var names = new[] { "Status.Stun", "Damage.Fire", "Damage.Ice", "Damage" };

            var first = GameplayTagsGenerator.GenerateCode(names, DefaultOptions());
            var second = GameplayTagsGenerator.GenerateCode(names, DefaultOptions());

            Assert.AreEqual(first, second);
        }

        [Test]
        public void GenerateCode_KeywordSegment_PrefixedWithAt()
        {
            var code = GameplayTagsGenerator.GenerateCode(new[] { "class" }, DefaultOptions());

            StringAssert.Contains("@Class", code);
        }

        [Test]
        public void GenerateCode_NullNames_Throws()
        {
            Assert.Throws<ArgumentNullException>(
                () => GameplayTagsGenerator.GenerateCode(null!, DefaultOptions()));
        }

        [Test]
        public void GenerateCode_EmptyNamespace_Throws()
        {
            var options = DefaultOptions();
            options.Namespace = "";

            Assert.Throws<ArgumentException>(
                () => GameplayTagsGenerator.GenerateCode(new[] { "Damage" }, options));
        }

        [Test]
        public void GenerateCode_EmptyClassName_Throws()
        {
            var options = DefaultOptions();
            options.ClassName = "";

            Assert.Throws<ArgumentException>(
                () => GameplayTagsGenerator.GenerateCode(new[] { "Damage" }, options));
        }
    }
}
