using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Localization;
using UnityEngine;

namespace Rubickanov.Localization.Editor
{
    /// <summary>
    /// Generates strongly-typed localization keys from Unity String Table Collections.
    /// </summary>
    public static class LocalizationKeysGenerator
    {
        private static LocalizationGeneratorSettings Settings => LocalizationGeneratorSettings.instance;

        [MenuItem("Tools/Generators/Localization")]
        public static void GenerateKeys()
        {
            var tables = FindAllStringTableCollections();

            if (tables.Count == 0)
            {
                Debug.LogWarning("[LocalizationKeysGenerator] No String Table Collections found.");
                return;
            }

            var code = GenerateCode(tables);
            WriteToFile(code);

            AssetDatabase.Refresh();
            Debug.Log($"[LocalizationKeysGenerator] Generated {Settings.OutputPath} with {tables.Count} table(s).");
        }

        private static Dictionary<string, List<string>> FindAllStringTableCollections()
        {
            var result = new Dictionary<string, List<string>>();

            var guids = AssetDatabase.FindAssets("t:StringTableCollection");

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var collection = AssetDatabase.LoadAssetAtPath<StringTableCollection>(path);

                if (collection == null) continue;

                var tableName = collection.TableCollectionName;
                var keys = new List<string>();

                var sharedData = collection.SharedData;
                if (sharedData != null)
                {
                    foreach (var entry in sharedData.Entries)
                    {
                        if (!string.IsNullOrEmpty(entry.Key))
                        {
                            keys.Add(entry.Key);
                        }
                    }
                }

                if (keys.Count > 0)
                {
                    result[tableName] = keys;
                }
            }

            return result;
        }

        private static string GenerateCode(Dictionary<string, List<string>> tables)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated by LocalizationKeysGenerator.");
            sb.AppendLine("// Do not modify manually. Run Tools/Generators/Localization to regenerate.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using Rubickanov.Localization;");
            sb.AppendLine($"namespace {Settings.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Strongly-typed localization keys generated from String Tables.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static class {Settings.ClassName}");
            sb.AppendLine("    {");

            var sortedTables = tables.OrderBy(t => t.Key).ToList();

            for (var i = 0; i < sortedTables.Count; i++)
            {
                var table = sortedTables[i];
                var className = SanitizeIdentifier(table.Key);

                sb.AppendLine($"        public static class {className}");
                sb.AppendLine("        {");
                sb.AppendLine($"            private const string Table = \"{table.Key}\";");
                sb.AppendLine();

                var sortedKeys = table.Value.OrderBy(k => k).ToList();

                foreach (var key in sortedKeys)
                {
                    var fieldName = SanitizeIdentifier(key);
                    sb.AppendLine($"            public static readonly LocalizationKey {fieldName} = new(Table, \"{key}\");");
                }

                sb.AppendLine("        }");

                if (i < sortedTables.Count - 1)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string SanitizeIdentifier(string input)
        {
            if (string.IsNullOrEmpty(input))
                return "_";

            var sanitized = Regex.Replace(input, @"[^a-zA-Z0-9_]", "_");

            if (char.IsDigit(sanitized[0]))
            {
                sanitized = "_" + sanitized;
            }

            sanitized = ToPascalCase(sanitized);

            if (IsCSharpKeyword(sanitized))
            {
                sanitized = "@" + sanitized;
            }

            return sanitized;
        }

        private static string ToPascalCase(string input)
        {
            var parts = input.Split('_', System.StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();

            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(part[0]));
                    if (part.Length > 1)
                    {
                        sb.Append(part.Substring(1).ToLowerInvariant());
                    }
                }
            }

            return sb.Length > 0 ? sb.ToString() : "_";
        }

        private static bool IsCSharpKeyword(string word)
        {
            var keywords = new HashSet<string>
            {
                "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
                "char", "checked", "class", "const", "continue", "decimal", "default",
                "delegate", "do", "double", "else", "enum", "event", "explicit",
                "extern", "false", "finally", "fixed", "float", "for", "foreach",
                "goto", "if", "implicit", "in", "int", "interface", "internal",
                "is", "lock", "long", "namespace", "new", "null", "object", "operator",
                "out", "override", "params", "private", "protected", "public",
                "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
                "stackalloc", "static", "string", "struct", "switch", "this", "throw",
                "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
                "ushort", "using", "virtual", "void", "volatile", "while"
            };

            return keywords.Contains(word.ToLowerInvariant());
        }

        private static void WriteToFile(string content)
        {
            var directory = Path.GetDirectoryName(Settings.OutputPath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory!);
            }

            File.WriteAllText(Settings.OutputPath, content);
        }
    }
}
