using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Localization;
using UnityEngine;

namespace Rubickanov.Localization.Editor
{
    /// <summary>
    /// Generates strongly-typed localization keys from Unity String Table Collections.
    /// </summary>
    public static class LocalizationKeysGenerator
    {
        private static LocalizationGeneratorSettings Settings => LocalizationGeneratorSettings.instance;

        private static readonly Regex IdentifierPattern = new(@"[^a-zA-Z0-9_]", RegexOptions.Compiled);

        private static readonly HashSet<string> CSharpKeywords = new(System.StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal", "default",
            "delegate", "do", "double", "else", "enum", "event", "explicit",
            "extern", "false", "finally", "fixed", "float", "for", "foreach",
            "goto", "if", "implicit", "in", "int", "interface", "internal",
            "is", "lock", "long", "namespace", "new", "null", "object", "operator",
            "out", "override", "params", "private", "protected", "public",
            "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
            "stackalloc", "static", "string", "struct", "switch", "this", "throw",
            "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
            "ushort", "using", "virtual", "void", "volatile", "while"
        };

        [MenuItem("Tools/Generators/Localization")]
        public static void GenerateKeys()
        {
            if (string.IsNullOrWhiteSpace(Settings.OutputPath))
            {
                Debug.LogError("[LocalizationKeysGenerator] OutputPath is empty. " +
                               "Configure it in Project Settings / Localization Generator.");
                return;
            }

            var tables = FindAllStringTableCollections();

            if (tables.Count == 0)
            {
                Debug.LogWarning("[LocalizationKeysGenerator] No String Table Collections found.");
                return;
            }

            var options = new LocalizationCodeOptions
            {
                Namespace = Settings.Namespace,
                ClassName = Settings.ClassName,
            };

            var code = GenerateCode(tables, options);
            WriteToFile(code);

            AssetDatabase.Refresh();
            Debug.Log($"[LocalizationKeysGenerator] Generated {Settings.OutputPath} with {tables.Count} table(s).");
        }

        private static Dictionary<string, List<string>> FindAllStringTableCollections()
        {
            var result = new Dictionary<string, List<string>>();

            var guids = AssetDatabase.FindAssets("t:StringTableCollection");

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var collection = AssetDatabase.LoadAssetAtPath<StringTableCollection>(path);

                if (collection == null) continue;

                var tableName = collection.TableCollectionName;
                var keys = new List<string>();

                var sharedData = collection.SharedData;
                if (sharedData != null)
                {
                    foreach (var entry in sharedData.Entries)
                    {
                        if (!string.IsNullOrEmpty(entry.Key))
                        {
                            keys.Add(entry.Key);
                        }
                    }
                }

                if (keys.Count > 0)
                {
                    result[tableName] = keys;
                }
            }

            return result;
        }

        /// <summary>
        /// Pure code generator. Produces a C# source string from a table-name → keys map.
        /// Deterministic: identical input + options yield identical output. Member names are
        /// de-duplicated per scope so realistic table layouts can't emit uncompilable output.
        /// </summary>
        public static string GenerateCode(IReadOnlyDictionary<string, List<string>> tables, LocalizationCodeOptions options)
        {
            if (tables == null) throw new System.ArgumentNullException(nameof(tables));
            if (string.IsNullOrEmpty(options.Namespace))
                throw new System.ArgumentException("Namespace must be non-empty.", nameof(options));
            if (string.IsNullOrEmpty(options.ClassName))
                throw new System.ArgumentException("ClassName must be non-empty.", nameof(options));

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated by LocalizationKeysGenerator.");
            sb.AppendLine("// Do not modify manually. Run Tools/Generators/Localization to regenerate.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using Rubickanov.Localization;");
            sb.AppendLine($"namespace {options.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Strongly-typed localization keys generated from String Tables.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static class {options.ClassName}");
            sb.AppendLine("    {");

            var sortedTables = tables.OrderBy(t => t.Key, System.StringComparer.Ordinal).ToList();

            // Distinct table names can sanitize to the same class identifier; the table classes
            // share the outer class scope, so disambiguate them just like nested members.
            var usedTableNames = new HashSet<string>(System.StringComparer.Ordinal);

            for (var i = 0; i < sortedTables.Count; i++)
            {
                var table = sortedTables[i];
                var tableClassName = MakeUniqueIdentifier(SanitizeIdentifier(table.Key), usedTableNames);

                var root = new KeyTreeNode();
                var sortedKeys = table.Value.OrderBy(k => k, System.StringComparer.Ordinal).ToList();

                foreach (var key in sortedKeys)
                    root.Insert(key.Split('.'), key);

                WriteTreeNode(sb, root, table.Key, tableClassName, "        ");

                if (i < sortedTables.Count - 1)
                    sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void WriteTreeNode(StringBuilder sb, KeyTreeNode node, string tableName,
            string className, string indent)
        {
            sb.AppendLine($"{indent}public static class {className}");
            sb.AppendLine($"{indent}{{");

            // Leaf fields, the "Table" const, and nested child classes all live in this one class
            // scope and must have unique identifiers or the generated file won't compile. Distinct
            // keys can sanitize to the same name (case-differing siblings "fire"/"Fire", "my-key"/
            // "my_key", or a leaf and a nested class both named "Settings"); disambiguate per scope.
            var usedNames = new HashSet<string>(System.StringComparer.Ordinal);

            bool emitsTable = node.Leaves.Count > 0 || node.Children.Count == 0;
            if (emitsTable)
            {
                // Reserve "Table" so a key that sanitizes to it gets suffixed instead of colliding
                // with the const that leaf fields reference.
                usedNames.Add("Table");
                sb.AppendLine($"{indent}    private const string Table = \"{tableName}\";");
                sb.AppendLine();
            }

            var sortedLeaves = node.Leaves
                .OrderBy(l => l.FieldName, System.StringComparer.Ordinal)
                .ThenBy(l => l.OriginalKey, System.StringComparer.Ordinal);
            foreach (var leaf in sortedLeaves)
            {
                var fieldName = MakeUniqueIdentifier(leaf.FieldName, usedNames);
                sb.AppendLine(
                    $"{indent}    public static readonly LocalizationKey {fieldName} = new(Table, \"{leaf.OriginalKey}\");");
            }

            if (node.Leaves.Count > 0 && node.Children.Count > 0)
                sb.AppendLine();

            var sortedChildren = node.Children.OrderBy(c => c.Key, System.StringComparer.Ordinal).ToList();
            for (var i = 0; i < sortedChildren.Count; i++)
            {
                var child = sortedChildren[i];
                var childClassName = MakeUniqueIdentifier(SanitizeIdentifier(child.Key), usedNames);
                WriteTreeNode(sb, child.Value, tableName, childClassName, indent + "    ");

                if (i < sortedChildren.Count - 1)
                    sb.AppendLine();
            }

            sb.AppendLine($"{indent}}}");
        }

        private static string MakeUniqueIdentifier(string name, HashSet<string> used)
        {
            if (used.Add(name))
                return name;

            // Preserve a leading "@" keyword escape on the suffixed form (e.g. "@class" -> "@class_2").
            var hasEscape = name.StartsWith("@", System.StringComparison.Ordinal);
            var bare = hasEscape ? name.Substring(1) : name;
            var prefix = hasEscape ? "@" : string.Empty;

            int n = 2;
            string candidate;
            do { candidate = $"{prefix}{bare}_{n++}"; } while (!used.Add(candidate));
            return candidate;
        }

        private sealed class KeyTreeNode
        {
            public readonly Dictionary<string, KeyTreeNode> Children = new();
            public readonly List<(string FieldName, string OriginalKey)> Leaves = new();

            public void Insert(string[] segments, string originalKey)
            {
                if (segments.Length == 1)
                {
                    Leaves.Add((SanitizeIdentifier(segments[0]), originalKey));
                    return;
                }

                var childKey = segments[0];
                if (!Children.TryGetValue(childKey, out var child))
                {
                    child = new KeyTreeNode();
                    Children[childKey] = child;
                }

                child.Insert(segments[1..], originalKey);
            }
        }

        private static string SanitizeIdentifier(string input)
        {
            if (string.IsNullOrEmpty(input))
                return "_";

            var sanitized = IdentifierPattern.Replace(input, "_");

            if (char.IsDigit(sanitized[0]))
            {
                sanitized = "_" + sanitized;
            }

            sanitized = ToPascalCase(sanitized);

            if (IsCSharpKeyword(sanitized))
            {
                sanitized = "@" + sanitized;
            }

            return sanitized;
        }

        private static string ToPascalCase(string input)
        {
            var parts = input.Split('_', System.StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();

            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(part[0]));
                    if (part.Length > 1)
                    {
                        sb.Append(part.Substring(1).ToLowerInvariant());
                    }
                }
            }

            return sb.Length > 0 ? sb.ToString() : "_";
        }

        private static bool IsCSharpKeyword(string word)
        {
            return CSharpKeywords.Contains(word.ToLowerInvariant());
        }

        private static void WriteToFile(string content)
        {
            var directory = Path.GetDirectoryName(Settings.OutputPath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory!);
            }

            File.WriteAllText(Settings.OutputPath, content);
        }
    }

    /// <summary>Options for <see cref="LocalizationKeysGenerator.GenerateCode"/>.</summary>
    public struct LocalizationCodeOptions
    {
        /// <summary>C# namespace for the generated class.</summary>
        public string Namespace;

        /// <summary>Name of the generated outer static class.</summary>
        public string ClassName;
    }
}
