using System.Collections.Generic;
using System.Linq;
using System.Text;
using Rubickanov.Codegen.Editor;

namespace Rubickanov.Localization.Editor
{
    /// <summary>
    /// Pure code generator for strongly-typed localization keys. Identifier sanitization and
    /// collision handling are delegated to the shared <see cref="IdentifierSanitizer"/>; keys are
    /// lowercased after their first character (lowercaseRemainder: true), so "DoT" becomes "Dot".
    /// </summary>
    public static class LocalizationKeysGenerator
    {
        /// <summary>
        /// Produces a C# source string from a table-name → keys map.
        /// Deterministic: identical input + options yield identical output. Member names are
        /// de-duplicated per scope so realistic table layouts can't emit uncompilable output.
        /// </summary>
        public static string GenerateCode(IReadOnlyDictionary<string, List<string>> tables, LocalizationCodeOptions options)
        {
            if (tables == null) throw new System.ArgumentNullException(nameof(tables));
            if (string.IsNullOrEmpty(options.Namespace))
                throw new System.ArgumentException("Namespace must be non-empty.", nameof(options));
            if (string.IsNullOrEmpty(options.ClassName))
                throw new System.ArgumentException("ClassName must be non-empty.", nameof(options));

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated by LocalizationKeysGenerator.");
            sb.AppendLine("// Do not modify manually. Run Tools/Generators/Localization to regenerate.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using Rubickanov.Localization;");
            sb.AppendLine($"namespace {options.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Strongly-typed localization keys generated from String Tables.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static class {options.ClassName}");
            sb.AppendLine("    {");

            var sortedTables = tables.OrderBy(t => t.Key, System.StringComparer.Ordinal).ToList();

            // Distinct table names can sanitize to the same class identifier; the table classes
            // share the outer class scope, so disambiguate them just like nested members.
            var usedTableNames = new HashSet<string>(System.StringComparer.Ordinal);

            for (var i = 0; i < sortedTables.Count; i++)
            {
                var table = sortedTables[i];
                var tableClassName = IdentifierSanitizer.MakeUnique(
                    IdentifierSanitizer.Sanitize(table.Key, lowercaseRemainder: true), usedTableNames);

                var root = new KeyTreeNode();
                var sortedKeys = table.Value.OrderBy(k => k, System.StringComparer.Ordinal).ToList();

                foreach (var key in sortedKeys)
                    root.Insert(key.Split('.'), key);

                WriteTreeNode(sb, root, table.Key, tableClassName, "        ");

                if (i < sortedTables.Count - 1)
                    sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void WriteTreeNode(StringBuilder sb, KeyTreeNode node, string tableName,
            string className, string indent)
        {
            sb.AppendLine($"{indent}public static class {className}");
            sb.AppendLine($"{indent}{{");

            // Leaf fields, the "Table" const, and nested child classes all live in this one class
            // scope and must have unique identifiers or the generated file won't compile. Distinct
            // keys can sanitize to the same name (case-differing siblings "fire"/"Fire", "my-key"/
            // "my_key", or a leaf and a nested class both named "Settings"); disambiguate per scope.
            var usedNames = new HashSet<string>(System.StringComparer.Ordinal);

            bool emitsTable = node.Leaves.Count > 0 || node.Children.Count == 0;
            if (emitsTable)
            {
                // Reserve "Table" so a key that sanitizes to it gets suffixed instead of colliding
                // with the const that leaf fields reference.
                usedNames.Add("Table");
                sb.AppendLine($"{indent}    private const string Table = \"{tableName}\";");
                sb.AppendLine();
            }

            var sortedLeaves = node.Leaves
                .OrderBy(l => l.FieldName, System.StringComparer.Ordinal)
                .ThenBy(l => l.OriginalKey, System.StringComparer.Ordinal);
            foreach (var leaf in sortedLeaves)
            {
                var fieldName = IdentifierSanitizer.MakeUnique(leaf.FieldName, usedNames);
                sb.AppendLine(
                    $"{indent}    public static readonly LocalizationKey {fieldName} = new(Table, \"{leaf.OriginalKey}\");");
            }

            if (node.Leaves.Count > 0 && node.Children.Count > 0)
                sb.AppendLine();

            var sortedChildren = node.Children.OrderBy(c => c.Key, System.StringComparer.Ordinal).ToList();
            for (var i = 0; i < sortedChildren.Count; i++)
            {
                var child = sortedChildren[i];
                var childClassName = IdentifierSanitizer.MakeUnique(
                    IdentifierSanitizer.Sanitize(child.Key, lowercaseRemainder: true), usedNames);
                WriteTreeNode(sb, child.Value, tableName, childClassName, indent + "    ");

                if (i < sortedChildren.Count - 1)
                    sb.AppendLine();
            }

            sb.AppendLine($"{indent}}}");
        }

        private sealed class KeyTreeNode
        {
            public readonly Dictionary<string, KeyTreeNode> Children = new();
            public readonly List<(string FieldName, string OriginalKey)> Leaves = new();

            public void Insert(string[] segments, string originalKey)
            {
                if (segments.Length == 1)
                {
                    Leaves.Add((IdentifierSanitizer.Sanitize(segments[0], lowercaseRemainder: true), originalKey));
                    return;
                }

                var childKey = segments[0];
                if (!Children.TryGetValue(childKey, out var child))
                {
                    child = new KeyTreeNode();
                    Children[childKey] = child;
                }

                child.Insert(segments[1..], originalKey);
            }
        }
    }

    /// <summary>Options for <see cref="LocalizationKeysGenerator.GenerateCode"/>.</summary>
    public struct LocalizationCodeOptions
    {
        /// <summary>C# namespace for the generated class.</summary>
        public string Namespace;

        /// <summary>Name of the generated outer static class.</summary>
        public string ClassName;
    }
}
